"$schema" = 'https://starship.rs/config-schema.json'

palette = 'p10k_rainbow'
format = '$os$all'

[palettes.p10k_rainbow]
blue = '4'
green = '2'
red = '1'
cyan = '6'
magenta = '5'
ink = '232'
success = '76'
error = '196'

[hostname]
disabled = true
ssh_symbol = ' '

[os]
disabled = false
style = 'bold fg:ink'

[os.symbols]
AIX = ' '
AlmaLinux = ' '
Alpaquita = ' '
Alpine = ' '
ALTLinux = ' '
Amazon = ' '
Android = ' '
AOSC = ' '
Arch = ' '
Artix = ' '
Bluefin = ' '
CachyOS = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Elementary = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = ' '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = ' '
InstantOS = ' '
Ios = '󰀷 '
Kali = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
Nobara = ' '
OpenBSD = ' '
OpenCloudOS = ' '
openEuler = ' '
openSUSE = ' '
OracleLinux = '󰺡 '
PikaOS = ' '
Pop = ' '
Raspbian = ' '
Redhat = '󱄛 '
RedHatEnterprise = '󱄛 '
Redox = '󰀘 '
RockyLinux = ' '
Solus = ' '
SUSE = ' '
Ubuntu = ' '
Ultramarine = ' '
Unknown = ' '
Uos = ' '
Void = ' '
Windows = '󰍲 '
Zorin = ' '

[container]
disabled = true
symbol = ' '

[directory]
style = 'bold fg:blue'
read_only = ' 󰌾'

[git_branch]
symbol = ' '
style = 'bold fg:green'

[git_status]
style = 'bold fg:green'

[jobs]
style = 'bold fg:cyan'

[python]
style = 'bold fg:blue'
symbol = ' '

[conda]
style = 'bold fg:blue'
symbol = ' '

[php]
style = 'bold fg:magenta'
symbol = ' '

[package]
style = 'bold fg:magenta'
symbol = '󰏗 '

[terraform]
style = 'bold fg:magenta'
symbol = ' '

[aws]
style = 'bold fg:red'
symbol = ' '

[nix_shell]
style = 'bold fg:cyan'
symbol = ' '


[character]
success_symbol = '[❯](bold fg:success)'
error_symbol = '[❯](bold fg:error)'

[azure]
symbol = ' '

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol = '󰂑 '
empty_symbol = '󰂎 '

[buf]
symbol = ' '

[bun]
symbol = ' '

[c]
symbol = ' '

[cpp]
symbol = ' '

[cmake]
symbol = ' '

[cobol]
symbol = ' '


[crystal]
symbol = ' '

[dart]
symbol = ' '

[deno]
symbol = ' '

[direnv]
symbol = ' '

[docker_context]
symbol = ' '

[dotnet]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[erlang]
symbol = ' '

[fennel]
symbol = ' '

[fortran]
symbol = ' '

[fossil_branch]
symbol = ' '

[gcloud]
symbol = '󱇶 '

[gleam]
symbol = ' '

[git_commit]
tag_symbol = '  '

[golang]
symbol = ' '

[gradle]
symbol = ' '

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = ' '

[helm]
symbol = ' '

[hg_branch]
symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[kotlin]
symbol = ' '

[kubernetes]
symbol = '󱃾 '

[lua]
symbol = ' '

[maven]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[meson]
symbol = '󰔷 '

[mojo]
symbol = '󰈸 '

[nats]
symbol = ' '

[netns]
symbol = '󰛳 '

[nim]
symbol = ' '

[nodejs]
symbol = ' '

[ocaml]
symbol = ' '

[odin]
symbol = '󰟢 '

[opa]
symbol = ' '

[openstack]
symbol = ' '

[perl]
symbol = ' '

[pijul_channel]
symbol = ' '

[pixi]
symbol = '󰏗 '

[pulumi]
symbol = ' '

[purescript]
symbol = ' '

[raku]
symbol = '󱖊 '

[red]
symbol = '󱍼 '

[rlang]
symbol = '󰟔 '

[ruby]
symbol = ' '

[rust]
symbol = '󱘗 '

[scala]
symbol = ' '

[shlvl]
symbol = '󰹍 '

[singularity]
symbol = ' '

[solidity]
symbol = ' '

[spack]
symbol = ' '

[status]
symbol = ' '

[sudo]
symbol = ' '

[swift]
symbol = ' '

[typst]
symbol = ' '

[vagrant]
symbol = ' '

[vlang]
symbol = ' '

[xmake]
symbol = ' '

[zig]
symbol = ' '
